apiVersion: v1
kind: Service
metadata:
  name: pythonflaskapp-service
spec:
  type: NodePort
  selector:
    app: pythonflaskapp
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30088
